# Análisis del índice de calor en Iquitos (2000–2024)

Este notebook parte del dataset limpio generado en `01_exploracion.ipynb`.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/processed/iquitos_horario.csv", parse_dates=["fecha_hora"])
df["anio"] = df["fecha_hora"].dt.year
df["mes"] = df["fecha_hora"].dt.month
df["hora"] = df["fecha_hora"].dt.hour
df.head()

                 fecha_hora  temperatura  punto_rocio  anio  mes  hora
0 2000-01-01 00:00:00-05:00         25.0         24.0  2000    1     0
1 2000-01-01 01:00:00-05:00         25.0         23.6  2000    1     1
2 2000-01-01 02:00:00-05:00         25.0         24.0  2000    1     2
3 2000-01-01 03:00:00-05:00         24.0         23.0  2000    1     3
4 2000-01-01 04:00:00-05:00         23.0         23.0  2000    1     4

$$HR = 100 \times \frac{e^{\frac{17.625 \cdot T_d}{243.04 + T_d}}}{e^{\frac{17.625 \cdot T}{243.04 + T}}}$$

In [6]:
# Fórmula de Magnus: humedad relativa a partir de la temperatura y el punto de rocío
numerador = np.exp(17.625 * df["punto_rocio"] / (243.04 + df["punto_rocio"]))
denominador = np.exp(17.625 * df["temperatura"] / (243.04 + df["temperatura"]))

df["humedad_relativa"] = 100 * numerador / denominador
df["humedad_relativa"].describe()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26052\1433177566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["humedad_relativa"] = 100 * numerador / denominador

count    197471.000000
mean         84.591474
std          12.088424
min          30.836886
25%          77.715244
50%          88.679561
75%          94.107970
max         100.000000
Name: humedad_relativa, dtype: float64

In [13]:
df[df["humedad_relativa"] < 0]

Empty DataFrame
Columns: [fecha_hora, temperatura, punto_rocio, anio, mes, hora, 94.19101183405704, 91.95146683042387, 94.14864502241811, 100.0, 95.28050470364268, 83.5653445347348, 78.9202680701639, 70.47582088918257, 62.92958329531055, 62.22651784699078, 66.3818887938788, 70.29306142592459, 72.25862568930162, 74.30236303611939, 83.6769551752209, 88.67956137467019, 83.78747242805218, 79.0585121873896, 74.62820502423824, 65.01074996458017, 66.5821913857855, 74.46601257025355, 94.10581804007525, 62.71443976755973, 59.27401124880873, 58.445589633486186, 59.501583031997214, 84.58222979066468, 92.47449811830609, 57.797298024105714, 73.30375468472468, 91.89343814488669, 95.87171549669345, 56.045143115119764, 53.01351873864528, 90.23322652420384, 88.7589455109383, 72.69546161061415, 74.33521026919057, 78.78071949348664, 83.45262666598398, 88.59935257199315, 97.02473741830013, 68.8124838641661, 88.14427552074834, 91.8347893761904, 95.85651824746932, 67.99377352527185, 81.73656558895809, 91.36808417317935, 73.64299590012162, 83.73234961805122, 95.82587279106997, 94.06252427588008, 75.81858529426795, 86.22345560421888, 94.23292497092102, 96.41000840186355, 92.00888400052644, 66.17996487728405, 58.79575055298673, 81.38430034286966, 94.13798167409631, 76.80736076202786, 88.83751596451741, 95.84123754804762, 88.2271743116917, 97.03571226018123, 91.49045536193128, 75.36535821707002, 78.58837582919173, 81.80996009312997, 75.2065294447288, 94.99762073385126, 72.866865390855, 92.21206533472252, 88.51830793896133, 83.58775479523352, 91.86419181215088, 84.20248990010974, 70.05672312403225, 91.42959202232244, 95.81042336368797, 94.0187570010377, 84.68754380187383, 62.555360655713685, 78.44744220055775, 58.09725478359217, 69.87192274116438, 70.10874183711726, 95.88682989764682, 69.45299436061887, 94.12728946305282, 56.28299102683274, ...]
Index: []

[0 rows x 12127 columns]